### PR TITLE
Add FlushMetrics octane listener

### PR DESCRIPTION
**Pull request by djfrailey**
The FlushMetrics listener may be used with Laravel Octanes **RequestTerminated** event which emulates the same functionality that **register_shutdown_function** provides when PHP-FPM or mod_php

### CODE REVIEW

**Comment by jszobody** [comment]
Thanks for this. Looks like it still needs some work, yeah? I don't see you wiring up the `RequestTerminated` event anywhere, yet.

Also, there's no need to open both an issue and a PR. If you're going to submit a PR (and that's awesome!) feel free to skip the issue, it's just redundant at that point.

**Comment by djfrailey** [comment]
My understanding is that the package itself can't wire up an Octane event listener. Octane event listeners are different from normal Laravel event listeners in the way that they're registered, which is in the Octane configuration file: https://github.com/laravel/octane/blob/1.x/config/octane.php

I'm more or less wanting to provide the event with the laravel-metrics package as a convenience to the end user, otherwise everyone is writing this if they use Octane.

**Comment by jszobody** [comment]
The `octane.php` file is a convenient way for app developers to wire up listeners themselves, sure. But Octane is then just looping through those and calling `listen` on them just like any other event listener:

https://github.com/laravel/octane/blob/1.x/src/OctaneServiceProvider.php#L90-L94

I would expect that packages like this one should still auto-wire up events so users don't have to, and from reading the code I don't see any reason why we can't.

Also, there is a typo in your commit (`metrcis` instead of `metrics`). Which probably means this hasn't been tested in any real Octane app yet? I really don't want to merge this until someone tries it out in Octane and verifies it performs as expected.

**Comment by jszobody** [comment]
I'm jealous! Can't wait to use Octane myself.

**Comment by djfrailey** [comment]
Octane is pretty spiffy, we aren't quite using it in production yet, actually saw some performance loss when we initially attempted it. But all of the team has seen a 7-10x improvement when running things in our local environments.

That change you requested has been made, I've verified it works in Octane.

**Comment by djfrailey** [comment]
Hah! For some reason I thought you were talking about a commit message.

**Pull request merged**
