### PR TITLE
Add influx db 2 support

### PR DESCRIPTION
**Pull request by djfrailey**
This pull request introduces [influxdata/influx-php-client](https://github.com/influxdata/influxdb-client-php), but does not replace the previous InfluxDB library for backwards compatibility support.

The InfluxDBV1 and InfluxDBV2 adapters are responsible for:

- Generating Read/Write (udp included) connections from the underlying InfluxDB Client.
- Generating Points data structures.
- Calling the appropriate writePoints (IDBv1) or write (IDBv2) methods.

The STS\Metrics\Drivers\InfluxDB Driver now accepts an AbstractInfluxDBAdapter which will either be a V1 or a V2 adapter based on the configured `version` in metrics.php, with Version 2 being the default.

### CODE REVIEW

**Comment by djfrailey** [comment]
WriteAPI::getOption is currently throwing an error, this isn't ready to merge just yet.

**Comment by djfrailey** [comment]
Alright, I believe this is ready. WriteAPI::getOption was throwing an error because I hadn't configured my organization, which is not listed as a required configuration parameter in their documentation ¯\_(ツ)_/¯

**Comment by djfrailey** [comment]
Yes, I am running V2 and so far have not ran into any issues.

**Comment by jszobody** [comment]
@djfrailey I just released v2 of this package with a new driver, php8 types, and some small breaking changes (like the Facade namespace). This is a good time to get this merged in now with the new major release. 

I just merged master, resolved conflicts, and converted all the phpdoc comments to types in your adapter/driver code. 

Can you take a look at this now before I merge? Tests are passing, but since I still don't have access to a IDBv2 backend I can't do any real-world testing. If you can sign-off on these changes, I'll merge and tag a minor update to this package.

Thanks!

**Comment by nmalcolm** [comment]
I gave this a test since it seems to be the only library supporting v2, but I got an error.

```
PHP Fatal error:  Uncaught TypeError: STS\Metrics\Drivers\InfluxDB::format(): Return value must be of type InfluxDB\Point, InfluxDB2\Point returned in /project/vendor/stechstudio/laravel-metrics/src/Drivers/InfluxDB.php:80
Stack trace:
#0 /project/vendor/stechstudio/laravel-metrics/src/Drivers/InfluxDB.php(92): STS\Metrics\Drivers\InfluxDB->format()
#1 [internal function]: STS\Metrics\Drivers\InfluxDB->STS\Metrics\Drivers\{closure}()
#2 /project/vendor/stechstudio/laravel-metrics/src/Drivers/InfluxDB.php(93): array_map()
#3 /project/vendor/stechstudio/laravel-metrics/src/Drivers/InfluxDB.php(59): STS\Metrics\Drivers\InfluxDB->send()
#4 /project/vendor/stechstudio/laravel-metrics/src/MetricsServiceProvider.php(119): STS\Metrics\Drivers\InfluxDB->flush()
#5 [internal function]: STS\Metrics\MetricsServiceProvider->STS\Metrics\{closure}()
#6 {main}
  thrown in /project/vendor/stechstudio/laravel-metrics/src/Drivers/InfluxDB.php on line 80
```

```
<?php

namespace App\Events;

use App\Models\Thing;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use STS\Metrics\Contracts\ShouldReportMetric;
use STS\Metrics\Metric;

class ThingCreated implements ShouldReportMetric
{
    use Dispatchable;
    use InteractsWithSockets;
    use SerializesModels;

    public $thing;

    /**
     * Create a new event instance.
     */
    public function __construct(Thing $thing)
    {
        $this->thing = $thing;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return array<int, \Illuminate\Broadcasting\Channel>
     */
    public function broadcastOn(): array
    {
        return [
            new PrivateChannel('channel-name'),
        ];
    }

    public function createMetric()
    {
        return (new Metric('foobar'))
            ->setValue(1)
            ->setTags([
                'type' => $this->thing->type,
            ]);
    }
}
```

**Comment by jszobody** [comment]
@nmalcolm Can you update and try now? I just updated this PR branch. 

I'm not running Influx 2 myself, so I'm flying a bit blind here. But I could see the code issue that you ran into, and hoping it works better now.

**Comment by nmalcolm** [comment]
@jszobody LGTM!

**Comment by jszobody** [comment]
@nmalcolm Super! I'm going to merge this and tag a new release.

**Pull request merged**
