### PR TITLE
add: prometheus driver

### PR DESCRIPTION
**Pull request by dmtar**

### CODE REVIEW

**Comment by jszobody** [comment]
@dmtar Hey thanks for this, looking good. Can you update the README in this PR with documentation for this new driver?

**Comment by dmtar** [comment]
Hey @jszobody Thanks. I will polish the things a bit and test out the driver internally, I hope to finish it next week.

One thing though, I introduced a requirement for php 8.1 in the composer, which is a breaking change for sure.
So if you decide to merge this it will be tagged with 3.x I suppose

As well it's currently limited to counters and gagues which I need to add somewhere in the readme :)

**Comment by dmtar** [comment]
@jszobody It's me again. It would be nice if we can merge at some point. I'm open for feedback

**Comment by jszobody** [comment]
Merged, and 2.4 released!

**Pull request merged**
